### ISSUE TITLE
disable coloration in code blocks

### ISSUE THREAD

**Issue by patatetom** [KeithLRobertson/markdown-viewer#30]
hi,

this is not an issue but rather a question : how to disable coloration and bold text in code blocks ?

the block marked as text continues to be coloured...

```text
 ` ` `text
 text here
 ` ` `
```

I use this in the configuration tab of the extension, but is there a simpler or more elegant way ?
```css
code {
    font-size: small;
    color: 333 !important;
}
code span {
    color: 333 !important;
    font-weight: normal !important;
}
```

really thanks for this FF extension :+1:
